version: '3.8'

services:
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "61616:61616"  
      - "2000:8161"     
    volumes:
      - activemq_data:/opt/activemq/data
      - activemq_conf:/opt/activemq/conf

volumes:
  activemq_data:
  activemq_conf: