version: '3.8'

services:
  main-db:
    image: postgres
    container_name: main-postgresql
    # restart: always
    environment:
      POSTGRES_USER: Merfolk
      POSTGRES_PASSWORD: ferocal12093
      POSTGRES_DB: main_db
    ports:
      - '2403:5432'
    # expose:
    #  - '1042'
    volumes:
      - postgresqlA:/var/lib/postgres

volumes:
  postgresqlA:







