version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:2.452.3
    container_name: jenkins-master
    ports:
      - '1222:8000' 
      - '1235:50000'
    networks:
      - jenkins
    volumes:
      - jenkins_home:/var/jenkins_home     
      - /var/run/docker.sock:/var/run/docker.sock  
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false  
    restart: unless-stopped

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins_home: 