version: '3.8'
  
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      POSTGRES_PASSWORD: your_password
      POSTGRES_USER: your_user
      POSTGRES_DB: MainDB
    ports:
      - "5432:5432"
    volumes:
      - timescale-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  timescale-data:


# learn moore about it 